config:
  target: "http://localhost:3000"
  phases:
    - duration: 60
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
    - duration: 60
      arrivalRate: 5
      rampTo: 10
      name: Ramp up load
    - duration: 30
      arrivalRate: 10
      rampTo: 30
      name: Spike phase

scenarios:
  - name: /reviews
    flow:
      - get:
          url: "/reviews"
  - name: /reviews/:id
    flow:
      - get:
          url: "/reviews/{{ $randomNumber(1, 1000000) }}"
  - name: /reviews/meta
    flow:
      - get:
          url: "/reviews/meta"




